### POST /api/auth/forgot-password
POST {{local}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "tavongamatikiti@gmail.com"
}

###

### PUT /api/auth/reset-password/:token
PUT {{local}}/api/auth/reset-password/095c6d5662d7233f1d90d92885eed3a758945541
Content-Type: application/json

{
  "password": "updatedPassword"
}

###

